// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#include <hardware/pio.h>
#include <config.h>
#include <hardware/clocks.h>
#include <pico/stdlib.h>

// --- //
// pwm //
// --- //

#define pwm_wrap_target 0
#define pwm_wrap 8
#define pwm_pio_version 0

/**
 * \brief Configure PIO for PWM
 */
static const uint16_t pwm_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0x80a0, //  2: pull   block
    0xa047, //  3: mov    y, osr
    0xe001, //  4: set    pins, 1
    0x0045, //  5: jmp    x--, 5
    0xe000, //  6: set    pins, 0
    0x0087, //  7: jmp    y--, 7
    0x0000, //  8: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_program = {
    .instructions = pwm_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = pwm_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pwm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pwm_wrap_target, offset + pwm_wrap);
    return c;
}
#endif

class CameraDriver
{
public:

/**
 * \brief constructor.
 * \param pwm_pio_pin the pwm output pin to the controller enable pin.
 */
    CameraDriver(uint8_t pwm_pio_pin);

/**
 * \brief destructor.
 */
    ~CameraDriver();

/**
 * \brief reset to PIO.
 * \details PWM freqency will be set to zero until fps is specified
 */
    void reset();

/**
 * \brief Call periodically in a loop to update the internal finite state
 *  machine that controls the pwm.
 */
    void update();

/**
 * \brief Initialize PWM on PIO
 */
    void pwm_init(PIO pio, uint sm, uint offset, uint8_t pin, uint8_t enable_state);

/**
 * \brief Initialize edge detection
 */
    void edge_detection_init(PIO pio, uint sm_edge, uint8_t pin, uint8_t enable_state);

/**
 * \brief Edge detection
 */
    void process_edges(PIO pio, uint sm_edge);


// FOR POOLING EVENTS
/**
 * \brief Set PWM frequency
 */
    void set_pwm(PIO pio, uint sm, float duty_cycle, uint32_t freq);

/**
 * \brief Camera output pin
 */
    inline void set_pio_pwm_pin(uint8_t pwm_pio_pin)
    {
        gpio_deinit(DEFAULT_PIO_PWM_PIN);
        // Init new gpio pin.
        pwm_pio_pin_ = pwm_pio_pin;
        gpio_init(pwm_pio_pin_);
        gpio_set_dir(pwm_pio_pin_, 1);
        sm_ = DEFAULT_PIO_SM;
        uint offset = pio_add_program(pio0, &pwm_program); //FIXME pio0 is hard coded
        pwm_init(pio0, sm_, offset, pwm_pio_pin_, false); 
    }

/**
 * \brief PWM frequency -- Camera FPS
 */
    inline void set_pwm_freq(uint32_t pwm_freq)
    {pwm_freq_ = pwm_freq;}

/**
 * \brief PWM duty cycle-- shouldn't change from 0.5f
 */
    inline void set_pwm_duty_cycle(float pwm_duty)
    {pwm_duty_ = pwm_duty;}

/**
 * \brief Enable Camera Triggering
 */
    inline void set_enable_state(uint8_t enable_state)
    {pio_sm_set_enabled(pio_, sm_, bool(enable_state));}

// Read functions
/**
 * \brief Get PIO PWM PIN
 */
    inline uint8_t get_pio_pwm_pin() const
    {return pwm_pio_pin_;}

/**
 * \brief Get the state of the PIO PWM pin
 */
    inline float get_pwm_pin_state() const 
    {return pwm_pin_state_;}

/**
 * \brief Get PWM Frequency - current FPS
 */
    inline uint32_t get_pwm_freq() const 
    {return pwm_freq_;}

/**
 * \brief Get PWM Duty Cycle
 */
    inline float get_pwm_duty() const 
    {return pwm_duty_;}

/**
 * \brief Get camera trigger enable state
 */
    inline float get_enable_state() const 
    {return enable_state_;}

private:

/**
 * \brief Detect rise and fall events of PWM signal
 */
    void pwm_signal_status();

    // Declare data members
    uint8_t pwm_pio_pin_;
    uint8_t pwm_pin_state_;
    uint8_t enable_state_;
    uint32_t pwm_freq_;
    float pwm_duty_;
    bool pin_is_initialized_;
    PIO pio_;
    uint sm_;

    // Declare Constants
    static inline constexpr float DEFAULT_DUTY_CYCLE = 0.5f;
    static inline constexpr uint32_t DEFAULT_FREQ = 60;
    static inline constexpr uint8_t DEFAULT_PIO_PWM_PIN = CAM_TRIGGER_PIN;
    static inline constexpr uint DEFAULT_PIO_SM = 0;
};





